
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ANYOTHER COMEND COMSTARTuncommented  : ANYOTHER\n                    | ANYOTHER COMSTART uncommented COMEND uncommented '
    
_lr_action_items = {'ANYOTHER':([0,3,5,],[2,2,2,]),'$end':([1,2,6,],[0,-1,-2,]),'COMEND':([2,4,6,],[-1,5,-2,]),'COMSTART':([2,],[3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'uncommented':([0,3,5,],[1,4,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> uncommented","S'",1,None,None,None),
  ('uncommented -> ANYOTHER','uncommented',1,'p_omit_comments','parser_comments.py',11),
  ('uncommented -> ANYOTHER COMSTART uncommented COMEND uncommented','uncommented',5,'p_omit_comments','parser_comments.py',12),
]
